### ISSUE TITLE
Explore communication services and produce a shortlist of priority focus

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#105]
- [x] Explore the spreadsheet 
- [x] Choose a subset to focus based on how feasible would be to integrate
- [x] Browse the wireframe and come with questions that you might have
