### ISSUE TITLE
October 5th Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#126]
**Checklist**
Quick summary of endpoints to use. How to use each endpoint + a testing client is available in the documentation endpoint ([online dev version](https://appcivist-pb.herokuapp.com/api/doc)). Endpoints starting with **/#/** are suggested UI views.  The ones that are marked are already implemented and working
1. **Contributions**
   - [X] #127 Test POST contributions endpoint
   - [X] #128 Add "moderatorsonly" rule to the security rules for "deleting" contributions (only soft delete
   - [x]  Add versioning/auditing of contributions updates
   - [x] Create endpoints for updating statistics (upvote, downvote, flag) 
   - [x] Add endpoint to comment on contribution 
   - [ ] Modify endpoint to include an array of "inspirations" contributions for contribution of type proposals
   - [x] Add "authorGroups" to contributions to link to groups
   - [x] Implement etherpad wrapper
2. **New Assembly**
   - [x] New Assembly Linked Assemblies: add linked assemblies support to model and controller 
   - [ ] Check membership invitations to include also the roles
   - [ ] Upload Icon/Assembly Profile pictures => POST /file
3. **New Campaign**
   - [ ] Add suport for linked campaigns and linked components in the campaign
   - [ ] Linked Campaigns => GET /assembly/{id}/campaign/linked
4. **Notifications**
5. [ ] #111 User updates fixes
   - [ ] add to the list the first post of user forums
   - [x] add language to updates model
   - [x] check title and text fields
   - [ ] document how to display the user updates in the UI
   - [x] check the break of line in update description text
6. **Components**
   - [ ] #116 Test and document components endpoint, particularly adding contributions to an instance within a milestone
   - [ ] #114 Test and document assembly/group invitations POST /assembly/{id}/invitations to include invitation message
7. **Working Groups**
8. [x] Group endpoints testing
9. [ ] #125 PUT and DELETE endpoints
