### ISSUE TITLE
November 16 Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#131]
**Checklist**
Quick summary of endpoints to use. How to use each endpoint + a testing client is available in the documentation endpoint ([online dev version](https://appcivist-pb.herokuapp.com/api/doc)). Endpoints starting with **/#/** are suggested UI views.  The ones that are marked are already implemented and working
1. **Contributions**
   - [ ] Modify endpoint to include an array of "inspirations" contributions for contribution of type proposals
2. **New Assembly**
   - [ ] Check membership invitations to include also the roles
   - [ ] Upload Icon/Assembly Profile pictures => POST /file
3. **New Campaign**
   - [ ] Add suport for linked campaigns and linked components in the campaign
   - [ ] Linked Campaigns => GET /assembly/{id}/campaign/linked
4. **Notifications**
5. [ ] #111 User updates fixes
   - [ ] add to the list the first post of user forums
   - [ ] document how to display the user updates in the UI
6. **Components**
   - [ ] #116 Test and document components endpoint, particularly adding contributions to an instance within a milestone
   - [ ] #114 Test and document assembly/group invitations POST /assembly/{id}/invitations to include invitation message
7. **Working Groups**
8. [ ] #125 PUT and DELETE endpoints
