### ISSUE TITLE
Alpha version of tracking idea evolution

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#166]
- [ ] Add model support for idea evolution: from idea to proposal or other types of contributions
- [ ] Generalize model support to support "contribution" evolution (the evolution of a contribution from one type to another, or to from one contribution of the same type to others, e.g., a comment that inspires an idea, 1 or more ideas that inspire a proposal, etc.)
- [ ] Add alpha endpoint for querying the history of a contribution
