### ISSUE TITLE
Merge Phase 0 new features

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#169]
- [ ] Merge #164, 2cd48195c1dec816e4b6e3cc4ee756e9b4bd247b
- [ ] Merge #165, de04492baf5729157decf70a886f5f0e82c5a2ab 
- [ ] Merge #161, 51ad9e1bc9642766920052fa97208e708a4c5a48
