### ISSUE TITLE
November 4 - November 10

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#198]
**Backend**
- October push leftover (what's the status of these issues?)
  - [x] Push/commit #189 and #190
  - [x] Finish #191 Add resources to campaign 
  - [x] Finish group consensus #186 #187 #188  
- New issues
  - [ ] #196 Contribution Feedback extensions
  - [ ] #203 Public proposal and create etherpad revisions
  - [ ] #205 Notificaiton persistance

**Frontend**
- Quick changes
  - [x] [New homepage](https://github.com/socialappslab/appcivist-pb-client/issues/249)
  - [x] [Re-route anon campaign](https://github.com/socialappslab/appcivist-pb-client/issues/262)
  - [x] [Move ideas to bottom](https://github.com/socialappslab/appcivist-pb-client/issues/251)
  - [x] [show/hide contribution menu items](https://github.com/socialappslab/appcivist-pb-client/issues/268)
  - [x] [up/down buttons](https://github.com/socialappslab/appcivist-pb-client/issues/269)
  - [x] [Proposal status](https://github.com/socialappslab/appcivist-pb-client/issues/271)
  - [x] [Fix campaign links](https://github.com/socialappslab/appcivist-pb-client/issues/255)
  - [x] [Navigation minor changes](https://github.com/socialappslab/appcivist-pb-client/issues/250)
  - [x] [Link logout](https://github.com/socialappslab/appcivist-pb-client/issues/252)
  - [x] [Navigation scrolling](https://github.com/socialappslab/appcivist-pb-client/issues/256)
  - [x] [Navigation in small screens](https://github.com/socialappslab/appcivist-pb-client/issues/257)
  - [x] [Alignments](https://github.com/socialappslab/appcivist-pb-client/issues/258)
  - [x] [Remove my settings from comments](https://github.com/socialappslab/appcivist-pb-client/issues/261)
  - [x] [Move about info](https://github.com/socialappslab/appcivist-pb-client/issues/263)
  - [x] [Empty place holders](https://github.com/socialappslab/appcivist-pb-client/issues/265)
  - [x] [Contribution menu icon](https://github.com/socialappslab/appcivist-platform/issues/202) 
  - [x] [Replace checkbox in menu button](https://github.com/socialappslab/appcivist-pb-client/issues/278)
- More complex changes
  - [x] [i18n](https://github.com/socialappslab/appcivist-pb-client/issues/266)
  - [x] [Load proposals/ideas/discussions](https://github.com/socialappslab/appcivist-pb-client/issues/259)
  - [x] [Commenting](https://github.com/socialappslab/appcivist-platform/issues/198)
