### ISSUE TITLE
Implement Social Ideation AppCivist Connector and AppCivist adaptations for Social Ideation

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#470]
Before adding the callbacks, how does Social Ideation knows the ids of the assembly, campaign, workign groups and proposals has to connect to? Check how this works and make sure support is added to store this information if it is needed for the callback endpoints. 

Perhaps all we need is a configuration file for the appcivist connector to specify the endpoints, but then for each new campaign that is conected, the following will be needed: 
 
- [ ] The Assembly ID in which the campaign exists: aid
- [ ] The Campaign ID and its corresponding resource space ID: caid, sid
- [ ] The list of Working Groups IDs (which might correspond to Topics) inside the campaign: [{wgid, wgsi}, ...]
- [ ] Then, we might need to store the ids and resource space ids for each contribution that represents a proposal: cid, csid

Check with @joausaga  and @MarceMMAD to see if this support will be needed and how is it managed on social ideation end

**Comment by joausaga** [comment]
This we should solve by creating a new module (see ideascale) with its corresponding models, urls, views, etc.
