### ISSUE TITLE
Configure docker and continuous integration for AppCivist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#733]
Configure docker and continuous integration for: 
- [ ] [Frontend](https://github.com/socialappslab/appcivist-pb-client): App AngularJS
- [ ] [Backend](https://github.com/socialappslab/appcivist-platform): Play Framework, Java [docs](https://platform.appcivist.org/api/doc)  
- [ ] [Voting Backend](https://github.com/socialappslab/appcivist-voting-api): Rails [docs] (https://platform.appcivist.org/voting/docs/api/v0.html) 
- [ ] Postgres database for AppCivist

Current Deployment Settings Notes: 
- There is an `appcivist` user
- All components are in `/home/appcivisit/production/*`
- To deploy del frontend, run: 
```
$ sudo - appcivist
$ cd production/appcivist-pb-client
$ ./deploy.sh
```

- To deploy del backend, run: 
```
$ sudo - appcivist
$ cd production/appcivist-platform
$ ./activator stage 
$ sudo /etc/init.d/appcivist-backend restart
$ tail -f  /home/appcivist/production/appcivist-platform/target/universal/stage/logs/application.log
``` 

- To deploy of voting  backend, run: 
```
$ sudo - appcivist
$ cd production/appcivist-voting-api
$ git pull
$ sudo /etc/init.d/appcivist-voting-api restart
``` 

Backend SO: 
- Etherpad-lite (see `/home/etherpad/etherpad-lite`) : separated docker image
- RabbitMQ : separated docker image
- Postgres (appcivist, etherpad) : BD outside docker
- HTTP/Apache : frontend docker image
- abiword (dependency that must be installed for etherpad to work): same docker image than etherpad-lite
- Entity Manager : separated docker image
- Subscription Manager: separated docker image
