### ISSUE TITLE
Research Consent per Campaign

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#826]
- [ ][back] Extend the information model campaign to store a research consent text for the first time a user visits the campaign
- [ ][back] Participation model connects the user and the campaign, to store his/her reply to the consent form and mark that the user has visited the campaign at least once
- [ ][back] Endpoint to get participation in campaign for user
